### ISSUE TITLE
Blackwallet should be removed

### ISSUE THREAD

**Issue by moellere** [stellar/os-projects#1]
Given the hack and current status of Blackwallet, I strongly recommend removing it from the Wallet list.

**Comment by endingwithali** [comment]
I believe that keeping Blackwallet on the list of open source projects is a better move than removing it. 

1. It's a learning opportunity for the community on how to improve wallet security  
2. having it listed is beneficial for its recovery

And more. 

As we state on our [list of community wallets](https://www.stellar.org/lumens/wallets/):
> Disclaimer: Stellar.org does not own, maintain or operate any of these wallets.

I think a better alternative would be to put a warning under Blackwallet's listing stating that the wallet is currently compromised, as well as the general disclaimer about our (Stellar's) relationship to the wallets listed.
