### ISSUE TITLE
No one is handling pull requests

### ISSUE THREAD

**Issue by israellevin** [stellar/os-projects#41]
It seems like no one is handling the pull requests. If you add me as a collaborator I will gladly help out.

**Comment by bartekn** [comment]
@theaeolianmachine can you check it out?

**Comment by theaeolianmachine** [comment]
Hey @israellevin - we actually plan to deprecate this project and replace it with something a bit more robust on our website. In the meanwhile, I'll merge out the rest of the requests, but will put a disclaimer on the readme.

**Comment by israellevin** [comment]
Personally, I love the fact that contributions are made with git, but robust is good, so good luck with that.

Thank you for handling this :+1:
